### ISSUE TITLE
Zerotier container stops after join

### ISSUE THREAD

**Issue by Tooa** [bltavares/docker-images#3]
When I try to add my RPI to an existing network the container stops after printing `0 join` because `/usr/sbin/zerotier-one` dies  (see below).

The same command works when running your container on my notebook though. Is there a way, I can debug this issue? I can't find any log file and the service is not really verbose. 

Any clue? Do you know such behavior?

### Device

* Rpi 4 with `Raspbian GNU/Linux 10 (buster)`
* bltavares/zerotier:latest (as of today)

### Details

* On my Rpi the `<network_id>.local.conf` file is missing **after** `join`
* `--entrypoint=/bin/sh` for debug purpose

```bash
user@rpi:/opt/zerotier $ docker run -it --rm --entrypoint=/bin/sh --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --net=host -v $PWD/config:/var/lib/zerotier-one  --device=/dev/net/tun bltavares/zerotier
/ #  zerotier-cli info
Error connecting to the ZeroTier service: connection failed
Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
/ # /usr/sbin/zerotier-one -d
/ #  zerotier-cli info
200 info <client_id> 1.2.12 ONLINE
/ # zerotier-cli join <network_id>
0 join 
/ #  zerotier-cli info
Error connecting to the ZeroTier service: connection failed

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
user@rpi:/opt/zerotier $ ls -ahl
drwxrwxrwx  5 root root 4.0K May 28 14:44 config
user@rpi:/opt/zerotier $ sudo iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:9993
```

**Comment by bltavares** [comment]
It very likely means that the raspberry pi has not loaded the 'tun' module and the service is not being able to create the interface and crashing. The pi version don't load the module by default.

Try loading it before starting the service:

```sh
sudo modprobe tun
```
